sonar.projectKey=TrackingApp
sonar.projectName=TrackingApp

sonar.sources=src
sonar.tests=__tests__

sonar.test.inclusions=**/*.test.ts?(x)

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8